apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  labels:
    name: jupyter-notebook
    app: dask
spec:
  type: LoadBalancer
  ports:
    - port: {{jupyter.port}}
      targetPort: 8888
      name: jupyter-http
    - port: {{jupyter.lab_port}}
      targetPort: 8889
      name: jupyter-lab-http
  selector:
    name: jupyter-notebook
---
apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  labels:
    name: dask-scheduler
    app: dask
spec:
  type: LoadBalancer
  ports:
    - port: {{scheduler.tcp_port}}
      targetPort: 8786
      name: dask-scheduler-tcp
    - port: {{scheduler.http_port}}
      targetPort: 9786
      name: dask-scheduler-http
    - port: {{scheduler.bokeh_port}}
      targetPort: 8787
      name: dask-scheduler-bokeh
  selector:
    name: dask-scheduler
